# Generated by Django 3.1.6 on 2021-02-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_library', '0003_emprunts'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='books/'),
        ),
    ]
